// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgsqnqumjdwhupavfvyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnc3FucXVtamR3aHVwYXZmdnl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NzY2NDQsImV4cCI6MjA3MjU1MjY0NH0.P_hoy2wDgV_ixgS2pisVZpsrz9cjhM7-A1UWFZW0dnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});